server:
  port: 8000

spring:
  application:
    name: springboot-3-api

# logging:
#   level:
#     com.eastern.servicesmanager.mapper : debug

# ???????? ???????? ?????? ??????
# ??program arguments ?? --spring.profiles.active=dev
# ??VM options ?? -Dspring.profiles.active=dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:springboot_security;MODE=MySQL
    type: com.zaxxer.hikari.HikariDataSource

  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        # ??????????
        register: false
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        healthCheckCriticalTimeout: 120m
        preferIpAddress: true
        metadata:
          env: ${spring.profiles.active}
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}
        aclToken: 6a84480c-6043-4b3d-9448-c2a20a8beac5

---
spring:
  config:
    activate:
      on-profile: test

